import MenuStringId from "resources/MenuStringId";
const locEntries = [
    {
        id: 0,
        en: "Play",
        zh: "玩游戏",
        ja: "プレイ",
        ko: "플레이",
        nl: "Spelen",
        it: "Gioca",
        fr: "Jouer",
        de: "Spielen",
        ru: "\u0418\u0433\u0440\u0430\u0442\u044c",
        es: "Jugar",
        br: "Jogar",
        ca: "Jugar",
    },
    {
        id: 1,
        en: "Options",
        zh: "选项",
        ja: "オプション",
        ko: "환경설정",
        nl: "Opties",
        it: "Opzioni",
        fr: "Options",
        de: "Optionen",
        ru: "\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438",
        es: "Opciones",
        br: "Opções",
        ca: "Opcions",
    },
    {
        id: 2,
        en: "Extras",
        ja: "エクストラ",
        zh: "额外内容",
        ko: "부가 기능",
        nl: "Extra's",
        it: "Extra",
        br: "Extras",
        es: "Extras",
        fr: "",
        de: "Extras",
        ru: "\u0415\u0449\u0435 \u043a\u043e\u0435 \u0447\u0442\u043e",
        ca: "Extres",
    },
    {
        id: 3,
        en: "Bonus mode",
        ko: "",
        fr: "",
        de: "Bonusmodus",
        ru: "\u0411\u043e\u043d\u0443\u0441 \u0440\u0435\u0436\u0438\u043c",
    },
    {
        id: 4,
        en: "Full version",
        es: "Version completa",
        fr: "Version compl\u00e8te",
        de: "Vollversion",
        ru: "\u041f\u043e\u043b\u043d\u0430\u044f \u0432\u0435\u0440\u0441\u0438\u044f",
    },
    {
        id: 5,
        en: "Reset game",
        zh: "重置游戏",
        ja: "リセット",
        ko: "게임 초기화",
        nl: "Herstarten",
        it: "Azzera gioco",
        ca: "Reiniciar joc",
        br: "Reiniciar jogo",
        es: "Restablecer",
        fr: "R\u00e9initialiser",
        de: "Neu starten",
        ru: "\u0421\u0431\u0440\u043e\u0441 \u043f\u0440\u043e\u0433\u0440\u0435\u0441\u0441\u0430",
    },
    {
        id: 6,
        en: "Help",
        fr: "",
        de: "Hilfe",
        ru: "\u041f\u043e\u043c\u043e\u0449\u044c",
    },
    {
        id: 7,
        en: "About",
        fr: "À propos",
        de: "\u00dcber",
        ru: "\u041e\u0431 \u0438\u0433\u0440\u0435",
    },
    {
        id: 8,
        en: "Credits",
        es: "Creditos",
        fr: "Cr\u00e9dits",
        de: "Mitwirkende",
        ru: "\u0410\u0432\u0442\u043e\u0440\u044b",
    },
    {
        id: 9,
        en: "Music on",
        zh: "音乐打开",
        ja: "音楽：*オン",
        ko: "배경음 켜기",
        nl: "Muziek aan",
        it: "Musica: sì",
        ca: "Música activada",
        br: "Música on",
        es: "Música: si",
        fr: "Musique oui",
        de: "Musik an",
        ru: "\u041c\u0443\u0437\u044b\u043a\u0430 \u0432\u043a\u043b.",
    },
    {
        id: 10,
        en: "Music off",
        zh: "音乐关闭",
        ja: "音楽：*オフ",
        ko: "배경음 끄기",
        nl: "Muziek uit",
        it: "Musica: no",
        ca: "Música desactivada",
        br: "Música off",
        es: "Música: no",
        fr: "Musique non",
        de: "Musik aus ",
        ru: "\u041c\u0443\u0437\u044b\u043a\u0430 \u0432\u044b\u043a\u043b.",
    },
    {
        id: 11,
        en: "Sounds on",
        zh: "声音打开",
        ja: "効果音：*オン",
        ko: "효과음 켜기",
        nl: "Geluid aan",
        it: "Suoni: sì",
        ca: "Sons activats",
        br: "Sons on",
        es: "Sonido: si",
        fr: "Sons oui",
        de: "Ger\u00e4usche an",
        ru: "\u0417\u0432\u0443\u043a\u0438 \u0432\u043a\u043b.",
    },
    {
        id: 12,
        en: "Sounds off",
        ja: "効果音：*オフ",
        zh: "声音关闭",
        ko: "효과음 끄기",
        nl: "Geluid uit",
        it: "Suoni: no",
        ca: "Sons desactivats",
        br: "Sons off",
        es: "Sonido: no",
        fr: "Sons non",
        de: "Ger\u00e4usche aus",
        ru: "\u0417\u0432\u0443\u043a\u0438 \u0432\u044b\u043a\u043b.",
    },
    {
        id: MenuStringId.RESET_TEXT,
        en: "Are you sure you want to reset your progress?",
        zh: "你确定要*重置游戏*进度吗？",
        ja: "本当に*リセット*しますか？",
        ko: "게임을 초기화하시겠습니까?",
        nl: "Weet je zeker dat je je voortgang wilt wissen?",
        it: "Vuoi davvero azzerare i tuoi progressi?",
        ca: "Estàs segur que desitges reiniciar el teu progrés?",
        br: "Tem certeza de que deseja descartar seu progresso?",
        es: "¿Seguro que quieres borrar el progreso realizado?",
        fr: "Voulez-vous vraiment r\u00e9initialiser votre progression?",
        de: "M\u00f6chtest du deinen Fortschritt wirklich zur\u00fccksetzen?",
        ru: "\u0423\u0432\u0435\u0440\u0435\u043d\u044b \u0447\u0442\u043e \u0445\u043e\u0442\u0438\u0442\u0435 \u0441\u0431\u0440\u043e\u0441\u0438\u0442\u044c \u0438\u0433\u0440\u043e\u0432\u043e\u0439 \u043f\u0440\u043e\u0433\u0440\u0435\u0441\u0441?",
    },
    {
        id: 14,
        en: "Passable!",
        zh: "马马虎虎！",
        ja: "まずまず!",
        ko: "간신히 통과!",
        nl: "Voldoende!",
        it: "Accettabile!",
        ca: "Acceptable!",
        br: "Passável!",
        es: "¡No está mal!",
        fr: "Passable!",
        de: "Passabel!",
        ru: "\u0423\u0440\u043e\u0432\u0435\u043d\u044c \u043f\u0440\u043e\u0439\u0434\u0435\u043d!",
    },
    {
        id: 15,
        en: "Good!",
        zh: "好！",
        ja: "グッド!",
        ko: "좋아요!",
        nl: "Goed!",
        it: "Bene!",
        ca: "Bé!",
        br: "Bom!",
        es: "¡Bien!",
        fr: "Bien!",
        de: "Gut!",
        ru: "\u0425\u043e\u0440\u043e\u0448\u043e!",
    },
    {
        id: 16,
        en: "Great!",
        zh: "真棒！",
        ja: "グレート!",
        ko: "잘 했어요!",
        nl: "Geweldig!",
        it: "Ottimo!",
        ca: "Fantàstic!",
        br: "Ótimo!",
        es: "¡Genial!",
        fr: "Super!",
        de: "Prima!",
        ru: "\u041e\u0442\u043b\u0438\u0447\u043d\u043e!",
    },
    {
        id: 17,
        en: "Excellent!",
        zh: "好极了！",
        ja: "最高!",
        ko: "아주 잘 했어요!",
        nl: "Uitstekend!",
        it: "Eccellente!",
        ca: "Excellent!",
        br: "¡Excelente!",
        es: "Excelente!",
        fr: "Formidable!",
        de: "Hervorragend!",
        ru: "\u0421\u0443\u043f\u0435\u0440!",
    },
    {
        id: 18,
        en: "Level",
        zh: "关卡",
        ja: "レベル",
        ko: "레벨",
        it: "Livello",
        ca: "Nivell",
        br: "Nível",
        es: "Nivel",
        fr: "Niveau",
        de: "Level",
        ru: "\u0423\u0440\u043e\u0432\u0435\u043d\u044c",
    },
    {
        id: 19,
        en: "Time",
        zh: "时间",
        ja: "タイム",
        ko: "시간",
        nl: "Tijd",
        it: "Tempo",
        ca: "Temps",
        br: "Tempo",
        es: "Tiempo",
        fr: "Temps",
        de: "Zeit",
        ru: "\u0412\u0440\u0435\u043c\u044f",
    },
    {
        id: 20,
        en: "Star Bonus",
        zh: "星星奖励",
        ja: "スターボーナス",
        ko: "보너스 별",
        nl: "Sterrenbonus",
        it: "Bonus stelle",
        ca: "Bonus de estrelles",
        br: "Bônus de estrela",
        es: "Bonificación estrellas",
        fr: "Bonus \u00e9toile",
        de: "Sternenbonus",
        ru: "\u0411\u043e\u043d\u0443\u0441 \u0437\u0430 \u0437\u0432\u0435\u0437\u0434\u044b",
    },
    {
        id: 21,
        en: "Your Final Score",
        zh: "你的*最终得分",
        ja: "あなたの*最終*スコア",
        ko: "최종 점수",
        nl: "Je eindscore",
        it: "Punteggio finale",
        ca: "La teva puntuació final",
        br: "Sua pontuação final",
        es: "Puntuación final",
        fr: "Votre score final",
        de: "Dein Endpunktestand",
        ru: "\u0418\u0442\u043e\u0433\u043e\u0432\u044b\u0435 \u043e\u0447\u043a\u0438",
    },
    {
        id: 22,
        en: "Best Score",
        zh: "最佳得分",
        ja: "ベスト*スコア",
        ko: "최고 점수",
        nl: "Beste score",
        it: "Miglior punteggio",
        ca: "Millor puntuació",
        br: "Melhor pontuação",
        es: "Mejor puntuación",
        fr: "Meilleur score",
        de: "Beste punktzahl",
        ru: "\u041b\u0443\u0447\u0448\u0438\u0439 \u0440\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442",
    },
    {
        id: 23,
        en: "Score",
        zh: "得分",
        ja: "スコア",
        ko: "점수",
        nl: "Score",
        it: "Punteggio",
        ca: "Puntuació",
        br: "Pontuação",
        es: "Puntuación",
        fr: "Score",
        de: "Punktzahl",
        ru: "\u041e\u0447\u043a\u0438",
    },
    {
        id: 24,
        en: "Yes",
        zh: "是",
        ja: "はい",
        ko: "예",
        nl: "Ja",
        it: "Sì",
        ca: "Sí",
        br: "Sim",
        es: "Sí",
        fr: "Oui",
        de: "Ja",
        ru: "\u0414\u0430",
    },
    {
        id: 25,
        en: "No",
        zh: "否",
        ja: "いいえ",
        ko: "아니요",
        nl: "Nee",
        ca: "No",
        br: "Não",
        fr: "Non",
        de: "Nein",
        ru: "\u041d\u0435\u0442",
    },
    {
        id: 26,
        en: "Replay",
        zh: "重玩",
        ja: "やり直す",
        ko: "다시 하기",
        nl: "Opnieuw",
        it: "Rigioca",
        ca: "Repetir",
        br: "Repetir",
        es: "Repetir",
        fr: "Rejouer",
        de: "Wieder",
        ru: "\u0415\u0449\u0435 \u0440\u0430\u0437",
    },
    {
        id: 27,
        en: "Next",
        zh: "下一步",
        ja: "次へ",
        ko: "다음",
        nl: "Volgende",
        it: "Prossimo",
        ca: "Següent",
        br: "Próximo",
        es: "Siguiente",
        fr: "Suivant",
        de: "Weiter",
        ru: "\u0412\u043f\u0435\u0440\u0435\u0434",
    },
    {
        id: 28,
        en: "Menu",
        zh: "菜单",
        ja: "メニュー",
        ko: "메뉴",
        nl: "Menu",
        ca: "Menú",
        es: "Menú",
        fr: "Menu",
        de: "Men\u00fc",
        ru: "\u041c\u0435\u043d\u044e",
    },
    {
        id: 29,
        en: "Loading...",
        zh: "正在加载...",
        ja: "ロード中...",
        ko: "불러오는 중...",
        nl: "Bezig met laden...",
        it: "Caricamento in corso...",
        ca: "Carregant ...",
        br: "Carregando ...",
        es: "Cargando...",
        fr: "Chargement...",
        de: "Laden...",
        ru: "\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0430...",
    },
    {
        id: 30,
        en: "Total: %d",
        zh: "合计： %d",
        ja: "合計：%d",
        ko: "총 점수: %d",
        nl: "Totaal: %d",
        it: "Totale: %d",
        fr: "Total: %d",
        de: "Gesamt: %d",
        ru: "\u0412\u0441\u0435\u0433\u043e: %d",
    },
    {
        id: 31,
        en: "Ok",
        zh: "确定",
        ja: "OK",
        ko: "확인",
        nl: "Oké",
        ca: "Acceptar",
        es: "Aceptar",
        fr: "OK",
        de: "Ok",
        ru: "Ok",
    },
    {
        id: 32,
        en: "Collect %d stars to unlock this level pack",
        zh: "收集 %d 颗*星星*才能解锁*这一*关卡集",
        ja: "アンロック*するには* %d の*スターが*必要です",
        ko: "이 레벨 상자를 열려면 별 %d개를 모으세요.",
        nl: "Verzamel %d sterren om dit levelpakket te ontgrendelen",
        it: "Raccogli %d stelle per sbloccare questo pacchetto di livelli",
        ca: "Aconsegueix %d estrelles per desbloquejar aquest paquet de nivells",
        br: "Colete %d estrelas para liberar este nível",
        es: "Consigue %d estrellas para desbloquear este pack de niveles.",
        fr: "Recueillez %d \u00e9toiles pour d\u00e9verrouiller ce pack de niveaux",
        de: "Sammle %d Sterne, um dieses Levelpaket freizuschalten",
        ru: "\u0421\u043e\u0431\u0435\u0440\u0438\u0442\u0435 %d \u0437\u0432\u0435\u0437\u0434 \u0447\u0442\u043e\u0431\u044b \u043e\u0442\u043a\u0440\u044b\u0442\u044c \u043a\u043e\u0440\u043e\u0431\u043a\u0443",
    },
    {
        id: MenuStringId.CANT_UNLOCK_TEXT1,
        en: "You are missing",
        zh: "你还需要",
        ja: "アンロックには",
        ko: "이 상자를 열려면",
        nl: "Je mist",
        it: "Hai bisogno di",
        ca: "Encara necessites",
        br: "Você precisa de",
        es: "Necesitas",
        fr: "Il vous en manque",
        de: "Dir fehlen",
        ru: "\u0412\u0430\u043c \u043d\u0435\u0445\u0432\u0430\u0442\u0430\u0435\u0442 \u0432\u0441\u0435\u0433\u043e",
    },
    {
        id: MenuStringId.CANT_UNLOCK_TEXT2,
        en: "to unlock this box",
        zh: "才能解锁*这个盒子",
        ja: "が必要です",
        ko: "개가 더 필요해요.",
        nl: "om deze doos te openen",
        it: "per sblocc. la scatola",
        ca: "per desbloquejar aquesta caixa",
        br: "para liberar esta caixa",
        es: "para abrir esta caja",
        fr: "pour d\u00e9verrouiller bo\u00eete",
        de: "um dieses Box freizuschalten",
        ru: "\u0447\u0442\u043e\u0431\u044b \u043e\u0442\u043a\u0440\u044b\u0442\u044c \u043a\u043e\u0440\u043e\u0431\u043a\u0443",
    },
    {
        id: MenuStringId.CANT_UNLOCK_TEXT3,
        en: "Get more stars from the earlier levels",
        zh: "从先前的*关卡中*获取更多*星星",
        ja: "前の*レベルで*スターを*もっと*獲得*しましょう",
        ko: "이전 레벨에서 별을 더 모으세요.",
        nl: "Ontvang meer sterren uit de eerdere levels",
        it: "Ottieni altre stelle nei primi livelli",
        ca: "Pots aconseguir més estrelles en els nivells anteriors",
        br: "Obtenha mais estrelas em níveis anteriores",
        es: "Vuelve a jugar los niveles anteriores para obtener más estrellas",
        fr: "Recueillez plus d'\u00e9toiles dans les niveaux pr\u00e9c\u00e9dents",
        de: "Gewinne mehr Sterne in den niedrigeren Leveln",
        ru: "\u0421\u043e\u0431\u0435\u0440\u0438\u0442\u0435 \u0431\u043e\u043b\u044c\u0448\u0435 \u0437\u0432\u0435\u0437\u0434 \u0432 \u043f\u0440\u0435\u0434\u044b\u0434\u0443\u0449\u0438\u0445 \u0443\u0440\u043e\u0432\u043d\u044f\u0445",
    },
    {
        id: 37,
        en: "Check back for the new levels coming with the updates",
        fr: "Revenez pour d\u00e9couvrir de nouveaux niveaux avec les mises \u00e0 jour",
        de: "Komm bald wieder, neue Level kommen mit den Updates",
        ru: "\u041d\u043e\u0432\u044b\u0435 \u0443\u0440\u043e\u0432\u043d\u0438 \u0431\u0443\u0434\u0443\u0442 \u0434\u043e\u0431\u0430\u0432\u043b\u044f\u0442\u044c\u0441\u044f \u0441 \u0430\u043f\u0434\u0435\u0439\u0442\u0430\u043c\u0438",
    },
    {
        id: MenuStringId.ACHIEVEMENT_GAINED,
        en: "achievement gained!",
        es: "Logro obtenido!",
        fr: "r\u00e9alisation d\u00e9verrouill\u00e9e!",
        de: "Erfolg geschafft!",
        ru: "\u043e\u0442\u043a\u0440\u044b\u0442\u043e!",
    },
    {
        id: 39,
        en: "Continue",
        zh: "继续",
        ja: "続ける",
        ko: "계속",
        nl: "Doorgaan",
        it: "Continua",
        ca: "Continuar",
        br: "Continuar",
        es: "Continuar",
        fr: "Continuer",
        de: "Weiter",
        ru: "\u041f\u0440\u043e\u0434\u043e\u043b\u0436\u0438\u0442\u044c",
    },
    {
        id: 40,
        en: "Skip level",
        zh: "跳过关卡",
        ja: "スキップ",
        ko: "레벨 건너뛰기",
        nl: "Overslaan",
        it: "Salta livello",
        ca: "Ometre nivell",
        br: "Pular nível",
        es: "Saltar nivel",
        fr: "Passer",
        de: "\u00dcberspringen",
        ru: "\u041f\u0440\u043e\u043f\u0443\u0441\u0442\u0438\u0442\u044c",
    },
    {
        id: 41,
        en: "Level select",
        zh: "选择关卡",
        ja: "レベル*選択",
        ko: "레벨 선택",
        nl: "Level kiezen",
        it: "Sel. livello",
        ca: "Selecció de nivell",
        br: "Escolha nível",
        es: "Elegir nivel",
        fr: "Choisir niveau",
        de: "Levelauswahl",
        ru: "\u0412\u044b\u0431\u043e\u0440 \u0443\u0440\u043e\u0432\u043d\u044f",
    },
    {
        id: 42,
        en: "Main menu",
        zh: "主菜单",
        ja: "メイン*メニュー",
        ko: "주 메뉴",
        nl: "Hoofdmenu",
        it: "Menu di gioco",
        ca: "Menú principal",
        br: "Menu Princ.",
        es: "Menú princ",
        fr: "Menu principal",
        de: "Hauptmen\u00fc",
        ru: "\u0413\u043b\u0430\u0432\u043d\u043e\u0435 \u043c\u0435\u043d\u044e",
    },

    {
        id: MenuStringId.LANGUAGE,
        en: "Language",
        ru: "Язык",
        fr: "Langue",
        de: "Sprache",
        es: "Lingua",
        br: "Idioma",
        ca: "Idioma",
        it: "Lingua",
        nl: "Taal",
        ko: "언어",
        ja: "言語",
        zh: "语言",
    },
    {
        id: MenuStringId.DRAG_TO_CUT,
        en: "Drag to Cut",
        fr: "Glisser",
        de: "Ziehe: Schneide",
        ru: "Перетаскиванием",
        es: "",
    },
    {
        id: MenuStringId.CLICK_TO_CUT,
        en: "Click to Cut",
        fr: "Cliquer",
        de: "Klicke: Schneide",
        ru: "Щелчком",
        es: "",
    },
    {
        id: MenuStringId.LETS_PLAY,
        en: "Let's Play",
        fr: "C'est parti",
        de: "Lass uns spielen",
        ru: "Давайте поиграем",
        es: "",
    },
    {
        id: MenuStringId.MORE_CTR_FUN,
        en: "More Cut the Rope fun!",
        fr: "Toujours plus de Cut the Rope !",
        de: "Mehr Cut the Rope Spaß!",
        ru: "Еще больше веселья в игре Cut the Rope!",
    },
    {
        id: MenuStringId.SHARE_ELLIPSIS,
        en: "Share...",
        fr: "Partager...",
        de: "Teilen...",
        ru: "Поделиться...",
        es: "Compartir...",
    },
    {
        id: MenuStringId.SHARE,
        en: "Share",
        fr: "Partager",
        de: "Teilen",
        ru: "Поделиться",
        es: "Compartir",
    },
    {
        id: MenuStringId.CONGRATULATIONS,
        en: "Congratulations!",
        fr: "Félicitations!",
        de: "Gratulation!",
        ru: "Поздравляем!",
        es: "Enhorabuena!",
        br: "Parabéns!",
        ca: "Enhorabona!",
        it: "Congratulazioni!",
        nl: "Gefeliciteerd!",
        ko: "축하합니다!",
        zh: "恭喜！",
        ja: "おめでとう*ございます！",
    },
    {
        id: MenuStringId.GAME_FINISHED_TEXT,
        en: "You completed the game with %d stars!",
        fr: "Tu as terminé le jeu avec %d étoiles !",
        de: "Du hast das Spiel mit %d Sternen beendet!",
        ru: "Вы завершили игру со следующим количеством звезд: %d!",
        ca: "Has finalitzat el joc amb %d estrelles!",
        ko: "게임이 끝났습니다!",
        zh: "你已完成*该游戏！",
        ja: "ゲームを クリアしました！",
        es: "¡Has terminado el juego!",
        it: "Hai completato il gioco!",
        nl: "Je hebt de game uitgespeeld!",
        br: "Você terminou o jogo!",
    },
    {
        id: MenuStringId.SHARE_DRAWING,
        en: "I just found one of Om Nom's secret drawings!",
        fr: "Je viens juste de trouver un des dessins secrets de Om Nom !",
        de: "Ich habe gerade eine geheime Om-Nom-Zeichnung entdeckt!",
        ru: "Мною только что был обнаружен один из тайных рисунков Ам Няма!",
    },
    {
        id: MenuStringId.FOUND_DRAWING,
        en: "You found a drawing!",
        fr: "Tu as trouvé un dessin !",
        de: "Du hast die Zeichnung gefunden!",
        ru: "Вы обнаружили рисунок!",
    },
    {
        id: MenuStringId.SHOW_ME,
        en: "Show Me",
        fr: "Montre-moi",
        de: "Zeig es mir",
        ru: "Показать мне",
    },
    {
        id: MenuStringId.FREE_DOWNLOAD,
        en: "Free Download",
        fr: "Téléchargement gratuit",
        de: "Kostenloser Download",
        ru: "Бесплатная загрузка",
    },
    {
        id: MenuStringId.SITE_DESC,
        en: "Cut the Rope is a fun game where you feed candy to the curiously cute green monster Om-nom.",
        fr: "Cut the Rope est un jeu amusant dans lequel tu dois nourrir Om Nom, un curieux petit monstre.",
        de: "Cut the Rope ist ein lustiges Spiel, wobei du dem kuriosem, niedlichem Monster Om-nom Süßigkeiten fütterst.",
        ru: "Cut the Rope   это веселая игра, в которой вы кормите сладостями любопытного и милого монстра по имени Ам Ням.",
    },
    {
        id: MenuStringId.SITE_TITLE,
        en: "Om Nom is Om Line - Cut the Rope for the Web",
        fr: "Om Nom est om ligne - Cut the Rope version web",
        de: "Om Nom ist Om Line - Cut the Rope für das Internet",
        ru: "Ам Ням в Ам Лайне – веб-версия игры Cut the Rope",
    },
    {
        id: MenuStringId.SITE_ACTION,
        en: 'Play the HTML5 version of "Cut the Rope"!',
        fr: "Joue à Cut the Rope dans sa version HTML5 !",
        de: 'Spiele die HTML5 Version von "Cut the Rope"!',
        ru: "Играйте в HTML5-версию игры Cut the Rope!",
    },
    {
        id: MenuStringId.RESET_HOLD_YES,
        en: 'Hold the "yes" button for 3 seconds to reset.',
        fr: 'Maintenir le doigt sur "Oui" pendant 3 secondes pour réinitialiser.',
        de: 'Halte zum Neustarten 3 Sekunden lang "Ja" gedrückt.',
        ru: 'Удерживайте "Да" в течение 3 секунд для сброса прогресса.',
        ko: "“예” 버튼을 3초 동안 누르면 초기화됩니다.",
        zh: "按住“是”按钮 3 秒即可重置。",
        ja: "はい」 のボタンを ３秒間*長押しで リセット",
        es: "Mantén pulsado 'Sí' durante 3 segundos para reiniciar.",
        it: "Tieni premuto il tasto 'sì' per 3 secondi per azzerare.",
        nl: "Houd de Ja-knop 3 seconden ingedrukt om opnieuw te beginnen.",
        br: "Segure o botão 'Sim' por 3 segundos para reiniciar.",
        ca: "Mantingues premut el botó 'sí' durant 3 segons per reiniciar.",
    },
    {
        id: MenuStringId.EVERYTHING_OFF,
        en: "everything off",
        fr: "tout couper",
        de: "alles aus",
        ru: "все отключено",
        es: "todo apagado",
        br: "todo off",
        ca: "tot desactivat",
        it: "tutto fuori",
        nl: "alles uit",
    },
    {
        id: MenuStringId.RELOAD_SD,
        en: "reload the game in SD",
        fr: "recharger le jeu en SD",
        de: "Spiel in SD neu laden",
        ru: "перезагрузить игру в SD",
    },
    {
        id: MenuStringId.RELOAD_HD,
        en: "reload the game in HD",
        fr: "recharger le jeu en HD",
        de: "Spiel in HD neu laden",
        ru: "перезагрузить игру в HD",
    },
    {
        id: MenuStringId.SLOW_TITLE,
        en: "A Little Too Slow...",
        fr: "Un peu trop lent",
        de: "Etwas zu langsam...",
        ru: "Как-то не очень быстро...",
    },
    {
        id: MenuStringId.SLOW_TEXT,
        en: "Om Nom is sad because your computer is running slow. We'll do our best, but there may be some slow-downs.",
        fr: "Om Nom est triste. Votre ordinateur est très lent. Nous ferons notre mieux, mais il est possible que le jeu ralentisse.",
        de: "Om Nom ist traurig, weil dein Computer so langsam ist. Wir geben unser Bestes, aber es kann trotzdem zu Verzögerungen kommen.",
        ru: 'Ам Ням опечален: у вас слишком медленный компьютер. Мы, конечно, постараемся, но игра у вас может "притормаживать".',
    },
    {
        id: MenuStringId.MUSIC,
        en: "Music",
        nl: "Muziek",
        it: "Musica",
        ca: "Música",
        fr: "Musique",
        de: "Musik",
        ru: "\u041c\u0443\u0437\u044b\u043a\u0430",
    },
    {
        id: MenuStringId.SOUNDS,
        en: "Sounds",
        nl: "Geluid",
        it: "Suoni",
        ca: "Sons",
        fr: "Sons oui",
        de: "Ger\u00e4usche",
        ru: "\u0417\u0432\u0443\u043a\u0438",
    },
    {
        id: MenuStringId.LEADERBOARDS,
        en: "Leaderboards",
        fr: "Classements",
        de: "Bestenlisten",
        ru: "Таблица рекордов",
    },
    {
        id: MenuStringId.ACHIEVEMENTS,
        en: "Achievements",
        fr: "Succès",
        de: "Erfolge",
        ru: "Достижения",
    },
    {
        id: MenuStringId.ACHIEVEMENT_UNLOCKED,
        en: "Achievement unlocked!",
        fr: "Succès débloqué !",
        de: "Erfolg freigeschaltet!",
        ru: "Новое достижение!",
    },
    {
        id: MenuStringId.UPGRADE_TO_FULL,
        en: "Get MANY MORE\n levels in the full version",
        fr: "De NOMBREUX autres niveaux\n sont disponibles dans la version complète!",
        de: "In der Vollversion gibt\n es noch VIEL MEHR Level!",
        ru: "Получите НАМНОГО БОЛЬШЕ\n уровней в полной версии!",
    },
    {
        id: MenuStringId.NAME,
        en: "Name",
        fr: "Nom",
        de: "Name",
        ru: "Имя",
    },
    {
        id: MenuStringId.AND_TEMPLATE,
        en: "{0} & {1}",
        fr: "{0} et {1}",
        de: "{0} und {1}",
        ru: "{0} и {1}",
        ca: "{0} i {1}",
    },
    {
        id: MenuStringId.BUY_FULL_GAME,
        en: "Buy Full Game",
        fr: "Acheter le jeu complet",
        de: "Vollversion kaufen",
        ru: "Купить полную версию",
    },
    {
        id: MenuStringId.SETTINGS,
        en: "Settings",
        fr: "Paramètres",
        de: "Einstellungen",
        ru: "Настройки",
        ca: "Configuració",
    },
    {
        id: MenuStringId.PRIVACY,
        en: "Privacy",
        fr: "Vie privée",
        de: "Datenschutz",
        ru: "Конфиденциальность",
    },

    /*
         {
         id: MenuStringId.,
         en: '',
         fr: '',
         de: '',
         ru: ''
         }
         */
];

export default locEntries;
